name: infobootleg
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  flutter_facebook_login:
  material_design_icons_flutter:
  http:
  html:
  flutter_widgets:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.svg
    - assets/images/facebook.svg
    - assets/images/email.svg
    - assets/images/user.svg
  fonts:
    - family: Lusitana
      fonts:
        - asset: assets/fonts/Lusitana/Lusitana-Bold.ttf
        - asset: assets/fonts/Lusitana/Lusitana-Regular.ttf
