name: infobootleg
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider:
  firebase_core:
  cloud_firestore:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/email.png
    - assets/images/user.png
  fonts:
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText-Regular.ttf
        - asset: assets/fonts/CrimsonText-Bold.ttf
